sudo: required
dist: trusty

language: rust

cache:
  - apt
  - cargo

addons:
  apt:
    packages:
      - libssl-dev

rust:
  - nightly

script:
- cargo clean
- cargo build
- cargo test

after_success: |
  cargo install --git https://github.com/xd009642/tarpaulin --force --branch develop cargo-tarpaulin
  cargo tarpaulin --ignore-tests --exclude-files bin/* --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
