sudo: required
dist: trusty
group: deprecated-2017Q4

language: rust

cache:
  - apt
  - cargo

addons:
  apt:
    packages:
      - libssl-dev

rust:
  - nightly-2017-12-03

script:
- cargo clean
- cargo build
- cargo test

after_success: |
  bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  cargo tarpaulin --ignore-tests --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
