[package]
name = "matrix_rocketchat"
version = "0.1.0"
authors = ["Andreas Brönnimann"]
license = "MIT OR Apache-2.0"

[lib]
name = "matrix_rocketchat"
path = "src/matrix-rocketchat/lib.rs"

[dependencies]
clap = {version = "2.1", features = ["yaml"]}
iron = { version = "0.4"}
lazy_static = "0.1"
router = "0.2"
serde = "0.8"
serde_derive = "0.8"
serde_yaml = "0.4"
slog = "1.3"
slog-json = "1.2"
slog-term = "1.3"
slog-stream = "1.2"
yaml-rust = "0.3"

[dev-dependencies]
matrix_rocketchat_test = { path = "tests/matrix-rocketchat-test" }
tempdir = "0.3"
