[package]
name = "matrix-rocketchat"
version = "0.1.0"
authors = ["Andreas Brönnimann"]
license = "MIT OR Apache-2.0"

[lib]
name = "matrix_rocketchat"
path = "src/matrix-rocketchat/lib.rs"

[dependencies]
clap = {version = "2.1", features = ["yaml"]}
serde = "0.8"
serde_derive = "0.8"
serde_yaml = "0.4"
slog = "1.3"
slog-json = "1.2"
slog-term = "1.3"
slog-stream = "1.2"
